remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Digitalisation in Physiotherapy"
description: "Hello, This is my blog explaining regarding digitalisation and innovations in the field of Physical therapy."
baseurl: # the subpath of your site, e.g. "/blog"
url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
mathjax:
  enable: # MathJax equations, e.g. true, false (default)
  combo:  # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags:  # "none", "ams" (default), "all"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: MV
liquid:
  error_mode: strict
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml
search_full_content: false # can have performance implications for large sites
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
author: Mahek 
  name:
  picture:
  email: voramahek7@gmail.com
  twitter: mahekvora
  links: 
    - title:
      url:
      icon:
footer_links:
  - title: 
    url: 
    icon: fas fa-rss-square
