remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Digitalisation in Physiotherapy"
description: "Innovations and Developments in Physiotherapy"
baseurl: https://voram.github.io/Digitalisation-in-Physiotherapy/
url:  
logo: # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: 
words_per_minute: # 200
mathjax:
  enable: # MathJax equations, e.g. true, false (default)
  combo:  # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags:  # "none", "ams" (default), "all"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "itim"
var tocToggle = document.getElementById('toc-toggle');
var tableOfContents = document.getElementById('markdown-toc');

function showToc(elem) {
  function getHeight() {
    elem.style.display = 'block';

    var height = elem.scrollHeight + 'px';

    elem.style.disply = '';

    return height;
  };

  var height = getHeight();
  elem.classList.add('js-toc-is-open');
  elem.style.height = height;

  window.setTimeout(function() {
    elem.style.height = '';
  }, 350);
};

function hideToc(elem) {
  elem.style.height = elem.scrollHeight + 'px';

  window.setTimeout(function() {
    elem.style.height = '0';
  }, 1);

  window.setTimeout(function() {
    elem.classList.remove('js-toc-is-open');
  }, 350);
};

function toggleToc(elem) {

  tocToggle.classList.toggle('js-toc-is-open');

  if (elem.classList.contains('js-toc-is-open')) {
    hideToc(elem);
    return;
  }

  showToc(elem);
};

if (tocToggle) {
  tocToggle.addEventListener("click", function(event) {
    toggleToc(tableOfContents);
  });
}
