remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
skin: "steel"
layout: "default"
{% include page-intro.html %}
<main id="main" class="page-content" aria-label="Content">
  <div class="inner">
    <div class="entry-wrap">
      <div class="entry-content">
        {{ Hello, I am a first year Health Informatics student. I am from India, and my age is 22 Years old. I can speak Hindi, Gujarati, German and English.
        Thanks to be here  :) }}
      </div>
      <aside class="entry-sidebar">
        {% include author %}
        {% if author_picture %}
          <img class="author-picture" src="{{  }}" alt="{{ Mahek Vora }}">
        {% endif %}
      </aside>
    </div>
  </div>
</main>
