remote_theme: vszhub/not-pure-poole
title: Digital health Interventions in Physiotherapy
description: Developments in digitization of Physiotherapy.
texture:
  title: Mahek Vora
  tagline: Digital Health Interventions in Physiotherapy
  date_format: "%b %-d, %Y"

  social_links:
  
    github: voram
    linkedIn: mahekv
