remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/dark.css"
locale: en-US
title: "Digitalisation in Physiotherapy"
description: "Innovations and Developments in Physiotherapy"
baseurl: https://voram.github.io/Digitalisation-in-Physiotherapy/
url:  
logo: 
date_format: "%B %-d, %Y"
read_time: 
words_per_minute: # 200
mathjax:
  enable: 
  combo: 
  tags: 
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "itim"
