remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
skin: steel
---
layout: default
---

{% include page-intro.html %}

<main id="main" class="page-content" aria-label="Content">
  <div class="inner">
    <div class="entry-wrap">
      <div class="entry-content">
        {{ Hi! I am Mahek Vora, currently in First year Health Informatics. I am from India, and 22 Years old. Thanks for bieng here on my Blog! }}
      </div>
      <aside class="entry-sidebar">
        {% include author %}
        {% if author_picture %}
          <img class="author-picture" src="{{ author_picture }}" alt="{{ author_name }}">
        {% endif %}
      </aside>
    </div>
  </div>
</main>
