remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
Description: Final exam for General Business Administration. Martikl Nr. 22206931
skin: steel
lang: en-US
email: voramahek7gmail.com
repository: "voram/Digitalisation-in-Physiotherapy"
author:
name: Mahek Vora
github_username: voram
