remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
skin: "steel"
lang: en-US
title: Digitalisation In Physiotherapy
email: voramahek7gmail.com
description: "Learning how the progress of Digital Health has hepled in Physiotherapy Treatments"
repository: "voram/Digitalisation-in-Physiotherapy"
author:
  name: Mahek Vora
github_username: voram
