remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"
locale: en-US
title: "Digitalisation in Physiotherapy"
description: "Innovations and Developments in Physiotherapy"
baseurl: https://voram.github.io/Digitalisation-in-Physiotherapy/
date_format: "%B %-d, %Y"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "itim"
